version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    networks:
      - javan-network
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials/gemini-api-service-account-mis.json
    volumes:
      - ./backend/credentials:/app/credentials:ro

  frontend:
    build: ./frontend
    ports:
      - "3001:80"
    depends_on:
      - backend
    networks:
      - javan-network

networks:
  javan-network:
    driver: bridge
